name: Snyk Security Scan

on:
  pull_request:
    branches:
      - main  # O la rama en la que desees realizar el escaneo

jobs:
  snyk-scan:
    runs-on: [self-hosted, linux]  # Esto indica que usas un runner auto-hospedado en Linux

    steps:
      # Paso 1: Verificar que el código está bien clonado y listo
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Paso 2: Configurar Snyk CLI
      - name: Install Snyk CLI
        run: |
          curl -sL https://static.snyk.io/snyk-install.sh | bash
          export PATH=$HOME/.snyk/bin:$PATH

      # Paso 3: Ejecutar el escaneo con Snyk y guardar el reporte en un archivo JSON
      - name: Run Snyk test and save the report locally
        run: snyk test --all-projects --json > ~/Documents/IMF/desarrolloSeguro/snyk-report.json

